//
// Generated file, do not edit! Created by opp_msgc 4.3 from networklayer/manetrouting/gr/GrRouteRequest.msg.
//

#ifndef _GRROUTEREQUEST_M_H_
#define _GRROUTEREQUEST_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API 
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API 
#  endif
#endif

// cplusplus {{
#include "IPv4Address.h"
#include "Coord.h"
// }}



/**
 * Class generated from <tt>networklayer/manetrouting/gr/GrRouteRequest.msg</tt> by opp_msgc.
 * <pre>
 * packet GrRouteRequest
 * {
 * 	IPv4Address src;
 * 	IPv4Address dst;
 * 	Coord srcPos;
 * 	Coord dstPos;
 * }
 * </pre>
 */
class INET_API GrRouteRequest : public ::cPacket
{
  protected:
    IPv4Address src_var;
    IPv4Address dst_var;
    Coord srcPos_var;
    Coord dstPos_var;

  private:
    void copy(const GrRouteRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const GrRouteRequest&);

  public:
    GrRouteRequest(const char *name=NULL, int kind=0);
    GrRouteRequest(const GrRouteRequest& other);
    virtual ~GrRouteRequest();
    GrRouteRequest& operator=(const GrRouteRequest& other);
    virtual GrRouteRequest *dup() const {return new GrRouteRequest(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual IPv4Address& getSrc();
    virtual const IPv4Address& getSrc() const {return const_cast<GrRouteRequest*>(this)->getSrc();}
    virtual void setSrc(const IPv4Address& src);
    virtual IPv4Address& getDst();
    virtual const IPv4Address& getDst() const {return const_cast<GrRouteRequest*>(this)->getDst();}
    virtual void setDst(const IPv4Address& dst);
    virtual Coord& getSrcPos();
    virtual const Coord& getSrcPos() const {return const_cast<GrRouteRequest*>(this)->getSrcPos();}
    virtual void setSrcPos(const Coord& srcPos);
    virtual Coord& getDstPos();
    virtual const Coord& getDstPos() const {return const_cast<GrRouteRequest*>(this)->getDstPos();}
    virtual void setDstPos(const Coord& dstPos);
};

inline void doPacking(cCommBuffer *b, GrRouteRequest& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, GrRouteRequest& obj) {obj.parsimUnpack(b);}


#endif // _GRROUTEREQUEST_M_H_
